### PR TITLE
Remove by word should consider other doc ids

### LINKED ISSUE #40: Deleting one document also causes other documents to disappear from searches
**Describe the bug**
The bug occurs in `lyra-0.0.1-beta-13`.

Sorry for opening several bugs, I was trying to compare Lyra with [MiniSearch](https://github.com/lucaong/minisearch) and ran into these issues.

**To Reproduce**

```javascript
const db = new Lyra({
  schema: {
    txt: "string",
  }
})

await db.insert({ txt: 'abc' })
//=> { id: 'J-LiSKu45O4d1phnVWvkc' }
await db.insert({ txt: 'abc' })
//=> { id: 'yx-s9o0-8I4uWcPsMyOWL' }
await db.insert({ txt: 'abcd' })
{ id: 'XoKJ6uWhRkftAt06UsdKo' }

await db.search({ term: 'abc', exact: true })
/* Returns what expected:
{
  elapsed: '814μs',
  hits: [
    { id: 'J-LiSKu45O4d1phnVWvkc', txt: 'abc' },
    { id: 'yx-s9o0-8I4uWcPsMyOWL', txt: 'abc' },
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ],
  count: 2
}
*/

// Delete one of the two documents containing term `"abc"`
db.delete('yx-s9o0-8I4uWcPsMyOWL')

await db.search({ term: 'abc', exact: true })
/* Returns no results, even if one doc with "abc" should still be in the index:
{
  elapsed: '770μs',
  hits: [
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined,
    undefined, undefined
  ],
  count: 0
}
*/
```

**Expected behavior**

Deleting one document should have no effect on other documents.

### PR DESCRIPTION
**Pull request by mateonunez**
This PR would fix #40.

Thanks a lot to @lucaong for supporting me in this bug.

The `removeByWord` now considers if the **docID** exists in _docIDs_ Set, then set the `node.end` as `false`. 
The `exact` param will stay in the function for future implementations.

### CODE REVIEW

**Comment by thomscoder** [comment]
LGTM 💯 Bug #40 seems to be fixed.

**Comment by micheleriva** [comment]
Thank you @lucaong, @thomscoder, and @mateonunez for working on this one

File: packages/lyra/src/prefix-tree/trie.ts [hunk 1]
```diff
@@ -112,12 +112,12 @@ export class Trie {
...
 
     function removeWord(node: TrieNode, _word: string, docID: string): boolean {
-      const [nodeWord /**_docs*/] = node.getWord();
+      const [nodeWord, docIDs] = node.getWord();
 
       if (node.end || (exact && node.end && nodeWord === word)) {
         node.removeDoc(docID);
 
-        if (node.children?.size) {
+        if (node.children?.size && docIDs.has(docID)) {
```
Comment (lucaong) [inline packages/lyra/src/prefix-tree/trie.ts:120]: This fixes the issue, but for the wrong reason :)

`docIDs.has(docID)` will always return `false` here, because in the previous line `node.removeDoc(docID)` removed the document from the set. As a result, `node.end = false` is never executed, so the whole `if` block here could be completely removed.

Never setting `node.end = false` on one hand fixes the issue, and does not cause any correctness problem. It just leaves a term in the trie, even when all documents associated to it were removed. This is fine, but will have performance impacts on large tries if a lot of documents are deleted: even when the set of documents associated to a term is empty, the term is never removed, so it is still considered in prefix and fuzzy search.

My recommendation: change the `if` condition to something like `node.children?.size && docIDs.size === 0`. That means: if after deleting this one document there are no more documents in the set pointed by this word, remove the word from the trie by making the node non-terminal.

Note that this still leaves one case uncovered, namely when the node its terminal but has no children. In that case, in order to really delete the term from the trie, one has to backtrack to the closest branching, and adjust the nodes to remove the "orphaned" suffix. This could be addressed in another issue, since again it does not affect correctness, but rather only performance in case of a large trie with many deleted terms (that without the proposed refactoring stay in the trie, even though they point to empty document sets).

I am confident that @micheleriva understands what I am pointing at, but otherwise I can offer some more explanation.

File: packages/lyra/src/prefix-tree/trie.ts [hunk 2]
```diff
@@ -112,12 +112,12 @@ export class Trie {
     if (!word) return false;
 
     function removeWord(node: TrieNode, _word: string, docID: string): boolean {
-      const [nodeWord /**_docs*/] = node.getWord();
+      const [nodeWord, docIDs] = node.getWord();
 
       if (node.end || (exact && node.end && nodeWord === word)) {
```
Comment (lucaong) [inline packages/lyra/src/prefix-tree/trie.ts:117]: not related to this PR (rather to #41), but still worth noting: this condition is completely equivalent to just `node.end`: that's because `x || (x && y)` is the same as just `x`. In the specific case, if `node.end` is true, the condition short circuits before the `||`. If it is false, then the part after the `||` is also false, because it's a chain of `&&` including `node.end`. Therefore, the whole `exact` logic can be removed with no effect.

Whether the resulting condition after removing the part after `||` is correct, I am not 100% sure (I would advise having more extensive tests), but for sure it is equivalent to the current one.

**Review by lucaong — COMMENTED** [review]
This fixes the issue, but for the "wrong reason" :) See the comment.
